mapeo_master = {

        "enero": 1, "febrero": 2, "marzo": 3, "abril": 4,
        "mayo": 5, "junio": 6, "julio": 7, "agosto": 8,
        "septiembre": 9, "octubre": 10, "noviembre": 11, "diciembre": 12,
        "jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6,
        "jul": 7, "aug": 8, "sep": 9, "oct": 10, "nov": 11, "dec": 12,
  
        "asia": "Asia",
        "ASIA": "Asia",
        "eu": "Europa",
        "EU": "Europa",
        "Eu": "Europa",
        "europa": "Europa",
        "latam": "Latinoamérica",
        "latinoamerica": "Latinoamérica",
        "Latinoamerica": "Latinoamérica",
        "norteamerica": "Norteamérica",
        "NORTEAMERICA": "Norteamérica",


        "dos mil diecinueve": "2019",
        "dos mil veinte": "2020",
        "2031": "2021",

        "1,609,517": "1609517",
        "1,869,817": "1869817",
        "1611336.00": "1611336",
        "1844733.00": "1844733",

        "ARGENTINA": "Argentina",
        "argentina": "Argentina",
        "Argetina": "Argentina",
        "BRASIL": "Brasil",
        "Brazil": "Brasil",
        "brasil": "Brasil",
        "CHILE": "Chile",
        "chile": "Chile",
        "COLOMBIA": "Colombia",
        "Kolombia": "Colombia",
        "colombia": "Colombia",
        "FRANCE": "Francia",
        "France": "Francia",
        "FRANCIA": "Francia",
        "francia": "Francia",
        "Espana": "España",
        "espña": "España",
        "españa": "España",
        "PERU": "Perú",
        "Peru": "Perú",
        "peru": "Perú",
        "KR": "Corea del Sur",
        "Korea": "Corea del Sur",
        "Corea": "Corea del Sur",
        "corea del sur": "Corea del Sur",
        "DINAMARCA": "Dinamarca",
        "Denmark": "Dinamarca",
        "dinamarca": "Dinamarca",
        "MEXICO": "México",
        "Mexico": "México",
        "Mejico": "México",
        "PORTUGAL": "Portugal",
        "SUECIA": "Suecia",
        "Sweden": "Suecia",
        "Latinoamerica": "Latinoamérica",
        "Norteamerica" : "Norteamérica",
   
        "SUPPORT": "Support",
        "support": "Support",
        "Soporte": "Support",
        "Sup": "Support",
        "TANK": "Tank",
        "tank": "Tank",
        "Tanque": "Tank",
        "tanque": "Tank",
        "DAMAGE": "Damage",
        "damage": "Damage",
        "DPS": "Damage",
        "dps": "Damage",
        "ENTRY": "Entry",
        "entry": "Entry",
        "Entrada": "Entry",
        "Entry Fragger": "Entry",
        "FLEX": "Flex",
        "flex": "Flex",
        "Flexible": "Flex",
        "IGL": "IGL",
        "igl": "IGL",
        "Igl": "IGL",
        "In Game Leader": "IGL",
        "Líder": "IGL",
        "LURKER": "Lurker",
        "lurker": "Lurker",
        "AWPER": "AWPer",
        "awper": "AWPer",
        "Sniper": "AWPer",
        "  Blaze Team": "Blaze Team",
        "BLAZE TEAM": "Blaze Team",
        "Blaze Team  ": "Blaze Team",
        "Blaze eTam": "Blaze Team",
        "BlazeTeam": "Blaze Team",
        "blaze team": "Blaze Team",
        "  Byte Force": "Byte Force",
        "BYTE FORCE": "Byte Force",
        "Byte Force  ": "Byte Force",
        "Byet Force": "Byte Force",
        "ByteForce": "Byte Force",
        "byte force": "Byte Force",
        "  Cyber Dragons": "Cyber Dragons",
        "CYBER DRAGONS": "Cyber Dragons",
        "Cyber Dragons  ": "Cyber Dragons",
        "CyberDragons": "Cyber Dragons",
        "cyber dragons": "Cyber Dragons",
        "CyberD ragons": "Cyber Dragons",
        "Crystal Gaming  ": "Crystal Gaming",
        "CRYSTAL GAMING": "Crystal Gaming",
        "Crystal Gamnig": "Crystal Gaming",
        "CrystalGaming": "Crystal Gaming",
        "crystal gaming": "Crystal Gaming",
        "Dark Wolves  ": "Dark Wolves",
        "Dar kWolves": "Dark Wolves",
        "dark wolves": "Dark Wolves",
        "DARK WOLVES": "Dark Wolves",
        "ECLIPSE": "Eclipse",
        "Eclipse  ": "Eclipse",
        "Eclpise": "Eclipse",
        "Iron Baers": "Iron Bears",
        "Iron Bears  ": "Iron Bears",
        "IronBears": "Iron Bears",
        "NEON STRIKERS": "Neon Strikers",
        "NeonStrikers": "Neon Strikers",
        "neon strikers": "Neon Strikers",
        "Neon Srtikers": "Neon Strikers",
        "  Neon Strikers": "Neon Strikers",
        "Neon Strikers  ": "Neon Strikers",
        "NOVA SQUAD": "Nova Squad",
        "Nova Squad  ": "Nova Squad",
        "Noav Squad": "Nova Squad",
        "nova squad": "Nova Squad",
        "NovaSquad": "Nova Squad",
        "  Nova Squad": "Nova Squad",
        "  Quantum Five": "Quantum Five",
        "QUANTUM FIVE": "Quantum Five",
        "ARCTIC FOXES": "Arctic Foxes",
        "Arctic Foxes  ": "Arctic Foxes",
        "Arctic Fxoes": "Arctic Foxes",
        "ArcticFoxes": "Arctic Foxes",
        "arctic foxes": "Arctic Foxes",
        "  Raptors GG": "Raptors GG",
        "RaptorsGG": "Raptors GG",
        "RAPTORS GG": "Raptors GG",
        "raptors gg": "Raptors GG",
        "Ratpors GG": "Raptors GG",
        "THUNDER ESPORTS": "Thunder Esports",
        "ThunderEsports": "Thunder Esports",
        "thunder esports": "Thunder Esports",
        "Thnuder Esports": "Thunder Esports",
        "  Thunder Esports": "Thunder Esports",
        "Thunder Esports  ": "Thunder Esports",
        "  Omega Team": "Omega Team",
        "OmegaTeam": "Omega Team",
        "omega team": "Omega Team",
        "Omgea Team": "Omega Team",
        "TITAN ESPORTS": "Titan Esports",
        "TitanEsports": "Titan Esports",
        "titan esports": "Titan Esports",
        "Tita nEsports": "Titan Esports",
        "  Titan Esports": "Titan Esports",
        "Titan Esports  ": "Titan Esports",
        "PHOENIX RISING": "Phoenix Rising",
        "PhoenixRising": "Phoenix Rising",
        "Phoenix Risign": "Phoenix Rising",
        "  Phoenix Rising": "Phoenix Rising",
        "Phoenix Rising  ": "Phoenix Rising",
        "StormGaming": "Storm Gaming",
        "STORM GAMING": "Storm Gaming",
        "storm gaming": "Storm Gaming",
        "Stomr Gaming": "Storm Gaming",
        "  Storm Gaming": "Storm Gaming",
        "Storm Gaming  ": "Storm Gaming",
        "ShadowLegion": "Shadow Legion",
        "shadow legion": "Shadow Legion",
        "Shado wLegion": "Shadow Legion",
        "  Shadow Legion": "Shadow Legion",
        "Shadow Legion  ": "Shadow Legion",
        "Adrian":       "Adrián",
        "Alvaro":       "Álvaro",
        "Angel":        "Ángel",
        "Asuncion":     "Asunción",
        "Cesar":        "César",
        "Encarnacion":  "Encarnación",
        "Ines":         "Inés",
        "Ivan":         "Iván",
        "Jose":         "José",
        "Lucia":        "Lucía",
        "Monica":       "Mónica",
        "Nicolas":      "Nicolás",
        "Noemi":        "Noemí",
        "Oscar":        "Óscar",
        "Raul":         "Raúl",
        "Rocio":        "Rocío",
        "Ruben":        "Rubén",
        "Tomas":        "Tomás",
        "Valentin":     "Valentín",
        "Veronica":     "Verónica",
        "Victor":       "Víctor",
        "Alvarez":      "Álvarez",
        "Angeles":      "Ángeles",
        "Benitez":      "Benítez",
        "Calderon":     "Calderón",
        "Cordoba":      "Córdoba",
        "Cortes":       "Cortés",
        "Diaz":         "Díaz",
        "Dominguez":    "Domínguez",
        "Duran":        "Durán",
        "Exposito":     "Expósito",
        "exposito":     "expósito",
        "Fernandez":    "Fernández",
        "Garcia":       "García",
        "Gimenez":      "Giménez",
        "Giron":        "Girón",
        "Gomez":        "Gómez",
        "Gutierrez":    "Gutiérrez",
        "Hernandez":    "Hernández",
        "Ibanez":       "Ibáñez",
        "Jimenez":      "Jiménez",
        "Leon":         "León",
        "Lopez":        "López",
        "Marin":        "Marín",
        "Martinez":     "Martínez",
        "Mendez":       "Méndez",
        "Millan":       "Millán",
        "Munoz":        "Muñoz",
        "Nunez":        "Núñez",
        "Pena":         "Peña",
        "Perez":        "Pérez",
        "Rios":         "Ríos",
        "Roldan":       "Roldán",
        "Saez":         "Sáez",
        "Sanchez":      "Sánchez",
        "Suarez":       "Suárez",
        "Vazquez":      "Vázquez",
        "Edicion":      "Edición",
        "Espana":       "España",
        "espana":       "españa",
        "Lider":        "Líder",
        "Manager":      "Mánager",
        "Psicologo":    "Psicólogo",
        "septimo":      "séptimo",
        "Triton":       "Tritón",
        "Vertigo":      "Vértigo",
        "2026-s1":      "Primera",
         "2025-s2":     "Segunda",
         "2"    :       "Segunda",
         "1":           "Primera",
         "Edición 1":   "Primera",
         "N/a":         "Sin datos",
         "3":           "Tercera",
         "s2":          "Segunda",
         "s1":          "Primera",
         " temporada":  "",
         "Infenro":     "Inferno",
         "Quantmu":     "Quantum",
         "Vortexclub":  "Vortex club",
         "Novasquad":   "Novas squad",
         "Neonstrikers": "Neon strikers",
         "Cyberd ragons":   "Cyber dragons",
         "Titanesports": "Titan esports",
         "Cyberdragons":    "Cyber dragons",
         "cyberdragons":    "Cyber dragons",
         "Noav squad": "Nova squad",
         "Crystalgaming": "Crystal gaming",
         "Phoenixrising":   "Phoenix rising",
         "Byteforce": "Byte force",
         "Arcticfoxes": "Arctic foxes",
         "Omegateam": "Omega team",
         "Quantmu five": "Quantum five",
         "Shadowlegion": "Shadow legion",
         "Zeinth": "Zenith",
         "Tita nesports": "Titan esports",
         "Ironbears": "Iron bears",
         "Vortexclub": "Vortex club",
         "Blaze etam": "Blaze team",
         "Arctic fxoes" : "Arctic foxes",
         "Thunderesports": "Thunder esports",
          "g2": "G2 Esports",
    "g2 esports": "G2 Esports",
    "g2esports": "G2 Esports",

    "fnatic": "Fnatic",
    "fntc": "Fnatic",

    "team liquid": "Team Liquid",
    "liquid": "Team Liquid",
    "teamliquid": "Team Liquid",

    "navi": "Natus Vincere",
    "na vi": "Natus Vincere",
    "natus vincere": "Natus Vincere",

    "faze": "FaZe Clan",
    "faze clan": "FaZe Clan",
    "fazee": "FaZe Clan",

    "vitality": "Team Vitality",
    "team vitality": "Team Vitality",

    "mad lions": "MAD Lions",
    "madlions": "MAD Lions",

    "heretics": "Team Heretics",
    "team heretics": "Team Heretics",

    "koi": "KOI",
    "movistar riders": "Movistar Riders",
    "riders": "Movistar Riders",

    "cloud9": "Cloud9",
    "c9": "Cloud9",

    "t1": "T1",
    "skt": "T1",

    "gen g": "Gen.G",
    "geng": "Gen.G",

    "edward gaming": "EDward Gaming",
    "edg": "EDward Gaming",

    "100 thieves": "100 Thieves",
    "100t": "100 Thieves",

    "astralis": "Astralis",
    "nip": "Ninjas in Pyjamas",
    "ninjas in pyjamas": "Ninjas in Pyjamas",

    "rogue": "Rogue",
    "bds": "Team BDS",
    "team bds": "Team BDS"
         








}
